import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import FullCalendar from'@fullcalendar/react';
import resourceTimelinePlugin from'@fullcalendar/resource-timeline';
import interactionPlugin,{Draggable}from'@fullcalendar/interaction';
import'./style.css';
const API='http://localhost:8000/api',key=(o,l)=>`${o}|${l??'_header_'}`,today=()=>new Date().toISOString().slice(0,10);
const prompts=['Which pick slips are unassigned?',"Show me today's picker workload.",'Which picker has the most scheduled work?'];
function App(){
 const[data,setData]=useState(null),[loadError,setLoadError]=useState(''),[tab,setTab]=useState('scheduler'),[view,setView]=useState('timeline'),[pickerFilter,setPickerFilter]=useState('all'),[orderFilter,setOrderFilter]=useState(''),[scheduleDate,setScheduleDate]=useState(today),[scheduleTime,setScheduleTime]=useState('08:00'),[selected,setSelected]=useState(null),[timelineTarget,setTimelineTarget]=useState(null),[contextSlip,setContextSlip]=useState(null),[notice,setNotice]=useState(''),[history,setHistory]=useState([]),[question,setQuestion]=useState(''),[isThinking,setIsThinking]=useState(false),list=useRef(null),calendar=useRef(null),chatEnd=useRef(null);
 const load=async()=>{try{const r=await fetch(`${API}/bootstrap`);if(!r.ok)throw Error(`Server returned ${r.status}`);setData(await r.json());setLoadError('')}catch(e){setLoadError(`Could not load the scheduler. ${e.message}`)}};
 useEffect(()=>{load()},[]);useEffect(()=>{if(!data||!list.current)return;const d=new Draggable(list.current,{itemSelector:'.slip',eventData:e=>JSON.parse(e.dataset.event)});return()=>d.destroy()},[data]);useEffect(()=>{calendar.current?.getApi().gotoDate(scheduleDate)},[scheduleDate]);useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth'})},[history,isThinking]);
 const persist=async(payload,revert)=>{const r=await fetch(`${API}/assignments`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){setNotice((await r.json().catch(()=>null))?.detail||'Assignment could not be saved.');revert?.();return false}setNotice(`Assigned ${payload.moveordernum} to ${payload.picker}.`);setSelected(null);setTimelineTarget(null);setContextSlip(null);await load();return true};
 const assign=(slip,picker,date=new Date(`${scheduleDate}T${scheduleTime}:00`))=>persist({moveordernum:slip.MoveOrderNum,moveorderlinenum:String(slip.MoveOrderLineNum),itemnumber:slip.ItemNumber,picker,pickdatetime:date.toISOString(),picking_duration_minutes:30});
 const save=(info,slip)=>assign(slip,info.event.getResources()[0]?.id,info.event.start).then(ok=>{if(!ok)info.revert?.()});
 const timelineRightClick=(arg,event)=>{event.preventDefault();const picker=arg.el.closest('[data-resource-id]')?.dataset.resourceId;if(!picker||!arg.date){setNotice('Right-click a picker time slot.');return}setTimelineTarget({picker,date:arg.date});setNotice(`Choose an unassigned pick slip for ${picker}.`)};
 const send=async e=>{e?.preventDefault();const text=question.trim();if(!text||isThinking)return;const next=[...history,{role:'user',content:text}];setHistory(next);setQuestion('');setIsThinking(true);try{const r=await fetch(`${API}/assistant`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:text,history})});const b=await r.json();setHistory([...next,{role:'assistant',content:r.ok?b.answer:`Error: ${b.detail}`}])}catch(err){setHistory([...next,{role:'assistant',content:`Error: ${err.message}`}])}finally{setIsThinking(false)}};
 if(loadError)return <main className="loading-state"><h1>PickSlip Scheduler</h1><p>{loadError}</p><button onClick={load}>Try again</button></main>;if(!data)return <main className="loading-state">Loading scheduler…</main>;
 const assigned=new Set(data.assignments.map(a=>key(a.moveordernum,a.moveorderlinenum))),matches=s=>`${s.MoveOrderNum} ${s.ItemNumber} ${s['Item Desc']}`.toLowerCase().includes(orderFilter.toLowerCase()),slips=data.pickslips.filter(s=>!assigned.has(key(s.MoveOrderNum,String(s.MoveOrderLineNum)))&&matches(s)),pickers=data.employees.filter(e=>pickerFilter==='all'||e.Name===pickerFilter),events=data.assignments.filter(a=>(pickerFilter==='all'||a.picker===pickerFilter)&&`${a.moveordernum} ${a.itemnumber||''}`.toLowerCase().includes(orderFilter.toLowerCase()));
 const filters=<div className="scheduler-toolbar"><label>Date<input type="date" value={scheduleDate} onChange={e=>setScheduleDate(e.target.value)}/></label><label>Picker<select value={pickerFilter} onChange={e=>setPickerFilter(e.target.value)}><option value="all">All pickers</option>{data.employees.map(e=><option key={e.Name}>{e.Name}</option>)}</select></label><label className="order-search">Search work<input value={orderFilter} onChange={e=>setOrderFilter(e.target.value)} placeholder="Order, item, or description"/></label><div className="view-toggle"><button className={view==='timeline'?'active':''} onClick={()=>setView('timeline')}>Timeline</button><button className={view==='assign'?'active':''} onClick={()=>setView('assign')}>Assign picker</button></div></div>;
 const slipButton=s=><button className={`slip ${selected&&key(selected.MoveOrderNum,String(selected.MoveOrderLineNum))===key(s.MoveOrderNum,String(s.MoveOrderLineNum))?'selected':''}`} key={key(s.MoveOrderNum,String(s.MoveOrderLineNum))} onClick={()=>{setSelected(s);setNotice(`Selected ${s.MoveOrderNum}. Drag it or right-click a picker time slot.`)}} data-event={JSON.stringify({title:s.MoveOrderNum,duration:'00:30',extendedProps:{slip:s}})}>{s.MoveOrderNum}<small>{s.ItemNumber} — {s['Item Desc']}</small></button>;
 const timeline=<section className="scheduler-layout"><div className="board"><p className="calendar-help">Drag a selected pick slip to a picker, or right-click a picker time slot to choose work without dragging.</p><FullCalendar ref={calendar} plugins={[resourceTimelinePlugin,interactionPlugin]} schedulerLicenseKey="CC-Attribution-NonCommercial-NoDerivatives" initialView="resourceTimelineDay" initialDate={scheduleDate} resources={pickers.map(e=>({id:e.Name,title:e.Name}))} events={events.map(a=>({id:key(a.moveordernum,a.moveorderlinenum),title:a.moveordernum,start:a.pickdatetime,resourceId:a.picker,extendedProps:a}))} editable droppable eventReceive={i=>save(i,i.event.extendedProps.slip)} eventChange={i=>save(i,{MoveOrderNum:i.event.extendedProps.moveordernum,MoveOrderLineNum:i.event.extendedProps.moveorderlinenum,ItemNumber:i.event.extendedProps.itemnumber})} slotLaneDidMount={a=>{a.el.oncontextmenu=e=>timelineRightClick(a,e)}} resourceAreaHeaderContent="Picker" slotMinTime="08:00:00" slotMaxTime="16:00:00" height="720"/></div><aside ref={list}><h2>Unassigned pick slips</h2><p className="work-count">{slips.length} available</p>{timelineTarget&&<div className="rightclick-picker"><strong>Assign to {timelineTarget.picker}</strong><small>{timelineTarget.date.toLocaleString()}</small><select defaultValue="" onChange={e=>{const slip=slips.find(s=>key(s.MoveOrderNum,String(s.MoveOrderLineNum))===e.target.value);if(slip)assign(slip,timelineTarget.picker,timelineTarget.date)}}><option value="" disabled>Choose a pick slip…</option>{slips.map(s=><option key={key(s.MoveOrderNum,String(s.MoveOrderLineNum))} value={key(s.MoveOrderNum,String(s.MoveOrderLineNum))}>{s.MoveOrderNum} — {s.ItemNumber}</option>)}</select></div>}<p className="assignment-notice">{notice}</p>{slips.map(slipButton)}</aside></section>;
 const pickerAssignment=<section className="scheduler-layout"><div className="board picker-drop-board"><div className="assignment-heading"><div><h2>Assign a picker to a pick slip</h2><p>Drag a picker from the right, or right-click a pick slip to select one.</p></div><label>Time<input type="time" value={scheduleTime} onChange={e=>setScheduleTime(e.target.value)}/></label></div><p className="assignment-notice">{notice}</p><div className="pickslip-drop-list">{slips.map(s=><article key={key(s.MoveOrderNum,String(s.MoveOrderLineNum))} className="pickslip-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const picker=e.dataTransfer.getData('picker');if(picker)assign(s,picker)}} onContextMenu={e=>{e.preventDefault();setContextSlip(s);setNotice(`Choose a picker for ${s.MoveOrderNum}.`)}}><div><strong>{s.MoveOrderNum}</strong><span>{s.ItemNumber} — {s['Item Desc']}</span></div><em>Drop picker here · right-click to choose</em>{contextSlip&&key(contextSlip.MoveOrderNum,String(contextSlip.MoveOrderLineNum))===key(s.MoveOrderNum,String(s.MoveOrderLineNum))&&<select autoFocus defaultValue="" onChange={e=>{if(e.target.value)assign(s,e.target.value)}}><option value="" disabled>Choose a picker…</option>{pickers.map(p=><option key={p.Name}>{p.Name}</option>)}</select>}</article>)}</div></div><aside className="picker-palette"><h2>Pickers</h2><p className="work-count">Drag a picker onto a pick slip.</p>{pickers.map(p=><button key={p.Name} className="picker-drag" draggable onDragStart={e=>e.dataTransfer.setData('picker',p.Name)}>{p.Name}</button>)}</aside></section>;
 const chat=<section className="chat-shell"><div className="chat-header"><div className="assistant-mark">AI</div><div><h2>Warehouse Manager Analyst</h2><p>Ask questions about current pick slips, pickers, and assignments.</p></div></div><div className="chat-messages">{history.length===0&&<div className="chat-welcome"><div className="welcome-icon">✦</div><h3>How can I help with the warehouse?</h3><p>I use the current scheduler data to answer operational questions.</p><div className="prompt-grid">{prompts.map(p=><button key={p} onClick={()=>setQuestion(p)}>{p}</button>)}</div></div>}{history.map((m,i)=><div key={i} className={`message-row ${m.role}`}><div className="message-avatar">{m.role==='user'?'You':'AI'}</div><div className="message-bubble">{m.content}</div></div>)}{isThinking&&<div className="message-row assistant"><div className="message-avatar">AI</div><div className="message-bubble thinking"><span/><span/><span/></div></div>}<div ref={chatEnd}/></div><form className="chat-composer" onSubmit={send}><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask about pick slips, workloads, or assignments…" disabled={isThinking}/><button disabled={!question.trim()||isThinking}>{isThinking?'Thinking…':'Send'}</button><small>Press Enter to send · Shift+Enter for a new line</small></form></section>;
 return <main><header><h1>PickSlip Scheduler</h1><nav><button onClick={()=>setTab('scheduler')}>Scheduler</button><button onClick={()=>setTab('ai')}>AI Warehouse Manager Analyst</button></nav></header>{tab==='scheduler'?<>{filters}{view==='timeline'?timeline:pickerAssignment}</>:chat}</main>}
createRoot(document.getElementById('root')).render(<App/>);
